name: Cost Monitoring and Reporting

on:
  # Run on schedule
  schedule:
    # Run weekly on Monday at 8:00 AM UTC
    - cron: '0 8 * * 1'
    # Also run on the 1st and 15th of each month
    - cron: '0 8 1,15 * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'report'
        type: choice
        options:
          - report
          - optimize
      recipient:
        description: 'Email recipient'
        required: false
        default: 'admin@giortech.com'

env:
  BILLING_ACCOUNT_ID: 0141E4-398D5E-91A063
  EMAIL_RECIPIENT: ${{ github.event.inputs.recipient || 'admin@giortech.com' }}

jobs:
  # Run cost monitoring for each application environment
  cost-monitoring-giortech:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
      
      - name: Load giortech dev config
        id: config
        run: |
          CONFIG_FILE=".github/config/project-config.yml"
          PROJECT_ID=$(yq e ".giortech.dev.project_id" $CONFIG_FILE)
          PROJECT_NUMBER=$(yq e ".giortech.dev.project_number" $CONFIG_FILE)
          
          echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT
          echo "project_number=$PROJECT_NUMBER" >> $GITHUB_OUTPUT
      
      - name: Google Auth for giortech
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ steps.config.outputs.project_number }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@${{ steps.config.outputs.project_id }}.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ steps.config.outputs.project_id }}
      
      - name: Generate cost report for giortech
        run: |
          echo "Generating cost report for giortech environments..."
          chmod +x ./scripts/cost_optimization.sh
          ./scripts/cost_optimization.sh report ${{ env.EMAIL_RECIPIENT }}

  cost-monitoring-waspwallet:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
      
      - name: Load waspwallet dev config
        id: config
        run: |
          CONFIG_FILE=".github/config/project-config.yml"
          PROJECT_ID=$(yq e ".waspwallet.dev.project_id" $CONFIG_FILE)
          PROJECT_NUMBER=$(yq e ".waspwallet.dev.project_number" $CONFIG_FILE)
          
          echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT
          echo "project_number=$PROJECT_NUMBER" >> $GITHUB_OUTPUT
      
      - name: Google Auth for waspwallet
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ steps.config.outputs.project_number }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@${{ steps.config.outputs.project_id }}.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ steps.config.outputs.project_id }}
      
      - name: Generate cost report for waspwallet
        run: |
          echo "Generating cost report for waspwallet environments..."
          chmod +x ./scripts/cost_optimization.sh
          ./scripts/cost_optimization.sh report ${{ env.EMAIL_RECIPIENT }}

  cost-monitoring-academyaxis:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
      
      - name: Load academyaxis dev config
        id: config
        run: |
          CONFIG_FILE=".github/config/project-config.yml"
          PROJECT_ID=$(yq e ".academyaxis.dev.project_id" $CONFIG_FILE)
          PROJECT_NUMBER=$(yq e ".academyaxis.dev.project_number" $CONFIG_FILE)
          
          echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT
          echo "project_number=$PROJECT_NUMBER" >> $GITHUB_OUTPUT
      
      - name: Google Auth for academyaxis
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ steps.config.outputs.project_number }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@${{ steps.config.outputs.project_id }}.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ steps.config.outputs.project_id }}
      
      - name: Generate cost report for academyaxis
        run: |
          echo "Generating cost report for academyaxis environments..."
          chmod +x ./scripts/cost_optimization.sh
          ./scripts/cost_optimization.sh report ${{ env.EMAIL_RECIPIENT }}

  # Consolidate reports
  consolidate-reports:
    needs: [cost-monitoring-giortech, cost-monitoring-waspwallet, cost-monitoring-academyaxis]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Generate consolidated report
        run: |
          mkdir -p ./reports
          CURRENT_DATE=$(date '+%Y-%m-%d')
          
          cat > ./reports/consolidated-cost-report-${CURRENT_DATE}.md << EOL
          # AcademyAxis.io Consolidated Cost Report
          
          **Date:** ${CURRENT_DATE}
          **Generated by:** GitHub Actions Cost Monitoring
          
          ## Organization Overview
          
          **Total Monthly Budget:** \$300 USD
          **Billing Account:** ${{ env.BILLING_ACCOUNT_ID }}
          
          ## Project Spending Summary
          
          ### giortech Application
          | Environment | Project ID | Budget | Status |
          |------------|------------|--------|--------|
          | Development | giortech-dev-project | \$50 | ✅ |
          | UAT | giortech-uat-project | \$50 | ✅ |
          | Production | giortech-prod-project | \$100 | ✅ |
          
          ### waspwallet Application
          | Environment | Project ID | Budget | Status |
          |------------|------------|--------|--------|
          | Development | waspwallet-dev-project | \$50 | ✅ |
          | UAT | waspwallet-uat-project | \$50 | ✅ |
          | Production | waspwallet-prod-project | \$100 | ✅ |
          
          ### academyaxis Application
          | Environment | Project ID | Budget | Status |
          |------------|------------|--------|--------|
          | Development | academyaxis-dev-project | \$50 | ✅ |
          | UAT | academyaxis-uat-project | \$50 | ✅ |
          | Production | academyaxis-prod-project | \$100 | ✅ |
          
          ## Recommendations
          
          - Monitor usage across all projects
          - Scale down unused development environments
          - Review log retention policies
          - Optimize Cloud Run instance allocation
          
          ## Dashboard Links
          
          Access cost dashboards in the Google Cloud Console for each project.
          EOL
      
      - name: Upload consolidated report
        uses: actions/upload-artifact@v4
        with:
          name: consolidated-cost-report-$(date '+%Y-%m-%d')
          path: ./reports/
          retention-days: 90