# File: .github/workflows/deploy-lb-dns.yml

name: Deploy Load Balancer and DNS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev, uat, prod)'
        required: true
        default: 'prod'
      application:
        description: 'Application to configure (giortech, waspwallet, academyaxis)'
        required: true
        default: 'giortech'

env:
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set project variables based on inputs
        id: vars
        run: |
          if [ "${{ github.event.inputs.application }}" = "giortech" ]; then
            if [ "${{ github.event.inputs.environment }}" = "prod" ]; then
              echo "PROJECT_ID=giortech-prod-project" >> $GITHUB_OUTPUT
            elif [ "${{ github.event.inputs.environment }}" = "uat" ]; then
              echo "PROJECT_ID=giortech-uat-project" >> $GITHUB_OUTPUT
            else
              echo "PROJECT_ID=giortech-dev-project" >> $GITHUB_OUTPUT
            fi
          elif [ "${{ github.event.inputs.application }}" = "waspwallet" ]; then
            echo "PROJECT_ID=waspwallet-${{ github.event.inputs.environment }}-project" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.application }}" = "academyaxis" ]; then
            echo "PROJECT_ID=academyaxis-${{ github.event.inputs.environment }}-project" >> $GITHUB_OUTPUT
          fi

      - name: Get Workload Identity configuration
        id: identity
        run: |
          # Use Terraform to get the Workload Identity Provider and Service Account from the target environment
          cd terraform/organization/giortech/${{ github.event.inputs.environment }}
          
          # Initialize Terraform
          terraform init
          
          # Get the outputs
          PROVIDER=$(terraform output -raw workload_identity_provider)
          SA_EMAIL=$(terraform output -raw service_account_email)
          
          echo "WI_PROVIDER=$PROVIDER" >> $GITHUB_OUTPUT
          echo "SA_EMAIL=$SA_EMAIL" >> $GITHUB_OUTPUT
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ steps.identity.outputs.WI_PROVIDER }}
          service_account: ${{ steps.identity.outputs.SA_EMAIL }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Setup Load Balancer and DNS
        run: |
          chmod +x scripts/setup-lb-dns.sh
          ./scripts/setup-lb-dns.sh \
            ${{ steps.vars.outputs.PROJECT_ID }} \
            ${{ github.event.inputs.application }} \
            ${{ github.event.inputs.environment }} \
            ${{ env.REGION }}