# File: .github/workflows/deploy-lb-dns.yml

name: Deploy Load Balancer and DNS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev, uat, prod)'
        required: true
        default: 'prod'
      application:
        description: 'Application to configure (giortech, waspwallet, academyaxis)'
        required: true
        default: 'giortech'

env:
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set project ID based on environment and application
        id: project
        run: |
          if [ "${{ github.event.inputs.application }}" = "giortech" ]; then
            if [ "${{ github.event.inputs.environment }}" = "prod" ]; then
              echo "PROJECT_ID=giortech-prod-project" >> $GITHUB_OUTPUT
              echo "SERVICE_ACCOUNT=github-actions-sa@giortech-prod-project.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
              echo "WORKLOAD_IDENTITY_PROVIDER=projects/371831144642/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_OUTPUT
            elif [ "${{ github.event.inputs.environment }}" = "uat" ]; then
              echo "PROJECT_ID=giortech-uat-project" >> $GITHUB_OUTPUT
              echo "SERVICE_ACCOUNT=github-actions-sa@giortech-uat-project.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
              echo "WORKLOAD_IDENTITY_PROVIDER=projects/28962750525/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_OUTPUT
            else
              echo "PROJECT_ID=giortech-dev-project" >> $GITHUB_OUTPUT
              echo "SERVICE_ACCOUNT=github-actions-sa@giortech-dev-project.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
              echo "WORKLOAD_IDENTITY_PROVIDER=projects/421191438459/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_OUTPUT
            fi
          # Add other applications as needed
          elif [ "${{ github.event.inputs.application }}" = "waspwallet" ]; then
            echo "PROJECT_ID=waspwallet-${{ github.event.inputs.environment }}-project" >> $GITHUB_OUTPUT
            echo "SERVICE_ACCOUNT=github-actions-sa@waspwallet-${{ github.event.inputs.environment }}-project.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.application }}" = "academyaxis" ]; then
            echo "PROJECT_ID=academyaxis-${{ github.event.inputs.environment }}-project" >> $GITHUB_OUTPUT
            echo "SERVICE_ACCOUNT=github-actions-sa@academyaxis-${{ github.event.inputs.environment }}-project.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
          fi
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ steps.project.outputs.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ steps.project.outputs.SERVICE_ACCOUNT }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Grant additional IAM permissions if needed
        run: |
          echo "Adding required IAM roles..."
          gcloud projects add-iam-policy-binding ${{ steps.project.outputs.PROJECT_ID }} \
            --member="serviceAccount:${{ steps.project.outputs.SERVICE_ACCOUNT }}" \
            --role="roles/compute.loadBalancerAdmin"
          
          gcloud projects add-iam-policy-binding ${{ steps.project.outputs.PROJECT_ID }} \
            --member="serviceAccount:${{ steps.project.outputs.SERVICE_ACCOUNT }}" \
            --role="roles/dns.admin"
          
          gcloud projects add-iam-policy-binding ${{ steps.project.outputs.PROJECT_ID }} \
            --member="serviceAccount:${{ steps.project.outputs.SERVICE_ACCOUNT }}" \
            --role="roles/certificatemanager.admin"
      
      - name: Setup Load Balancer and DNS
        run: |
          chmod +x scripts/setup-lb-dns.sh
          ./scripts/setup-lb-dns.sh \
            ${{ steps.project.outputs.PROJECT_ID }} \
            ${{ github.event.inputs.application }} \
            ${{ github.event.inputs.environment }} \
            ${{ env.REGION }}